# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Gavin Henry <ghenry@sentrypeer.org>
version: 2
updates:
  - package-ecosystem: cargo
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: main